### PR TITLE
Fix exitcode for fact to prevent failure using Facter 3.x

### PR DESCRIPTION
**Pull request by smoeding**
Facter 3.x seems to be more picky about the exit code when running external commands. The current code fails to run as the method returns nil to indicate that the command exited with an error code:

```
Error: Facter: error while resolving custom fact "ssh_server_version_full": undefined method `lines' for nil:NilClass
Error: Facter: error while resolving custom fact "ssh_server_version_major": undefined method `gsub' for nil:NilClass
Error: Facter: error while resolving custom fact "ssh_server_version_release": undefined method `gsub' for nil:NilClass
```

The patch is an easy fix to prevent that the sshd failure code reaches the Facter code.

Maybe using something like `sshd -d -t` is a better alternative in the long run?

### CODE REVIEW

**Comment by Sharpie** [comment]
Facter 3.0 was discarding the output of any command that returned a non-zero exit code. This was a regression and has been fixed in Facter 3.0.2.

See [FACT-1115](https://tickets.puppetlabs.com/browse/FACT-1115) for more details.

**Comment by smoeding** [comment]
I missed that fix...
I can confirm that the ssh module 2.8.1 again works correctly with Puppet 4.2.1/Facter 3.0.2. I therefore close this issue.
